version: '2'

services:
  server:
    container_name: minellius-server
    build: ./server
    ports:
      - "6080:6080"
    environment:
      - DEBUG=
      # true
      - PROTOCOL=
      # https
      - PORT=
      # 6080
      - DOMAIN=
      # minellius.evernightfireworks.com
      - SWAGGER_PATH=
      # document
      - DATABASE_USERNAME=
      # minellius_test
      - DATABASE_PASSWORD=
      # example_password
      - DATABASE_HOST=
      # 172.16.0.242
      - DATABASE_PORT=
      # 5432
      - DATABASE_TYPE=
      # postgres
      - DATABASE_NAME=
      # minellius
      - GITHUB_CLIENTID=
      # example_github_clientid
      - GITHUB_CLIENTSECRET=
      # example_github_clientsecret
      - GITHUB_REDIRECT_URI=
      # https://minellius.evernightfireworks.com/oauth/github
      - JWT_EXPIRATION=
      # 7 days
      - JWT_SECRETKEY=
      # example_jwt_secretkey
    restart: always
  crawler:
    container_name: minellius-crawler
    build: ./cralwer
    restart: always
  monitor:
    image: deltaskelta/docker-alertd
    container_name: minellius-monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitor/.docker-aled.yaml:/root/.docker-alertd.yaml
      # please copy .docker-aled.sample.yaml to ./monitor/.docker-aled.yaml and edit it
    